[2025-07-15T14:00:01.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-15T13:59:00+00:00 [queued]>
[2025-07-15T14:00:01.302+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-15T13:59:00+00:00 [queued]>
[2025-07-15T14:00:01.304+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-15T14:00:01.313+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_one_day_to_unprocessed> on 2025-07-15 13:59:00+00:00
[2025-07-15T14:00:01.318+0000] {standard_task_runner.py:60} INFO - Started process 2125 to run task
[2025-07-15T14:00:01.320+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prepare_raw_data_daily', 'extract_one_day_to_unprocessed', 'scheduled__2025-07-15T13:59:00+00:00', '--job-id', '585', '--raw', '--subdir', 'DAGS_FOLDER/extract_daily_to_s3.py', '--cfg-path', '/tmp/tmp53or9kvt']
[2025-07-15T14:00:01.322+0000] {standard_task_runner.py:88} INFO - Job 585: Subtask extract_one_day_to_unprocessed
[2025-07-15T14:00:01.358+0000] {task_command.py:423} INFO - Running <TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-15T13:59:00+00:00 [running]> on host 9b64cb4f6e82
[2025-07-15T14:00:01.412+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_raw_data_daily' AIRFLOW_CTX_TASK_ID='extract_one_day_to_unprocessed' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T13:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T13:59:00+00:00'
[2025-07-15T14:00:01.422+0000] {logging_mixin.py:188} INFO - Creating bucket 'unprocessed-files'...
[2025-07-15T14:00:01.427+0000] {logging_mixin.py:188} INFO - Loading raw CSV files...
[2025-07-15T14:00:01.431+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/data_generator/extract_raw_to_s3_daily.py", line 75, in extract_one_day_to_unprocessed
    raw_online = read_csv_from_s3(MINIO_RAW, ONLINE_FILE_NAME, TMSTMP)
  File "/opt/airflow/data_generator/extract_raw_to_s3_daily.py", line 37, in read_csv_from_s3
    obj = S3.get_object(Bucket=bucket, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
[2025-07-15T14:00:01.442+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=prepare_raw_data_daily, task_id=extract_one_day_to_unprocessed, execution_date=20250715T135900, start_date=20250715T140001, end_date=20250715T140001
[2025-07-15T14:00:01.450+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 585 for task extract_one_day_to_unprocessed (An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist; 2125)
[2025-07-15T14:00:01.493+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-15T14:00:01.505+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
